### ISSUE TITLE
Docker it

### ISSUE THREAD

**Issue by alexnederlof** [inventid/live-image-resize#1]
Create a simple docker file the runs this server. I can do it too. Just build in on top of nodejs and throw in your config. Make sure the database is also running on a mountable volume.

Vagrant boxes are so 2012. 

See https://docs.docker.com/examples/nodejs_web_app/

**Comment by PEM-FR** [comment]
"I can do it too" <-- please do :)

**Comment by rogierslag** [comment]
This is certainly planned, we are still beta testing this project in our production environment. I'll update the issue once it is dockerized

**Comment by rogierslag** [comment]
This has been done by now!

**Comment by PEM-FR** [comment]
:+1:  good job! Thank you!

**Comment by rogierslag** [comment]
There is a prefabricated build available on https://registry.hub.docker.com/u/rogierslag/live-image-resize/
