### ISSUE TITLE
Cache the redirect urls

### ISSUE THREAD

**Issue by alexnederlof** [inventid/live-image-resize#2]
From what I can tell in the code, the redirect URLs aren't stored. Since the images are immutable, why not cache those for let's say a week, so the loadbalancer can just serve those requests from memory for popular images

**Comment by alexnederlof** [comment]
Ah I see you set an expire date on the image at Amazon. Maybe make that configurable but also save it in the storage so you can tell everyone requesting the resource the link is valid until then.

**Comment by rogierslag** [comment]
Well, its immutable anyway. This only ensures that an image receives a request once per month. the redirect rules are saved to the SQLite database, and the image resources should live forever anyway
